// Optimize raw Pexels downloads → AVIF + WebP + JPEG + tiny blur placeholder.
// Reads from public/images/dishes/_raw/ → writes alongside in public/images/dishes/.
// Filenames stay slug-stable so the components don't need to know the source.

import sharp from "sharp";
import { readdir, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const SRC = "public/images/dishes/_raw";
const OUT = "public/images/dishes";

if (!existsSync(OUT)) await mkdir(OUT, { recursive: true });

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f));

console.log(`Optimizing ${files.length} files…`);

const blurMap = {};

for (const file of files) {
  const base = file.replace(/\.[^.]+$/, "");
  const input = join(SRC, file);

  // AVIF — best compression, modern browsers
  await sharp(input).resize({ width: 2400, withoutEnlargement: true }).avif({ quality: 70 }).toFile(join(OUT, `${base}.avif`));

  // WebP fallback
  await sharp(input).resize({ width: 2400, withoutEnlargement: true }).webp({ quality: 80 }).toFile(join(OUT, `${base}.webp`));

  // JPEG ultimate fallback (mozjpeg)
  await sharp(input).resize({ width: 2400, withoutEnlargement: true }).jpeg({ quality: 82, progressive: true, mozjpeg: true }).toFile(join(OUT, `${base}.jpg`));

  // 20px-wide blur placeholder, base64-encoded for next/image
  const blurBuf = await sharp(input).resize({ width: 20 }).blur(1).webp({ quality: 60 }).toBuffer();
  blurMap[base] = `data:image/webp;base64,${blurBuf.toString("base64")}`;

  console.log(`  ✓ ${base}`);
}

// Emit a TS-friendly blur map so next/image can use blurDataURL without
// runtime base64 work.
const blurOut = `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n` +
  `export const BLUR_DATA_URLS: Record<string, string> = ${JSON.stringify(blurMap, null, 2)};\n`;
await import("node:fs").then(({ writeFileSync }) =>
  writeFileSync(join(OUT, "blur-data.ts"), blurOut)
);

console.log(`Wrote ${OUT}/blur-data.ts`);
