// Single source of truth for site photography. All paths point to optimized
// files in /public/images/dishes/ (generated by scripts/optimize-images.mjs).
// next/image will serve AVIF/WebP automatically based on Accept headers.
//
// Credits live in /public/images/dishes/_credits.json — atribución a Pexels
// hasta que el cliente entregue fotografía propia del local.
//
// To swap a dish photo: drop a new 2400-wide source in
// /public/images/dishes/_raw/<slug>.jpg, re-run `node scripts/optimize-images.mjs`,
// and the rest of the app updates automatically.

import { BLUR_DATA_URLS } from "../../public/images/dishes/blur-data";

export type Photo = {
  id: string;
  src: string;          // path relative to /public
  blurDataURL: string;  // base64 webp for next/image placeholder="blur"
  alt: string;
};

function photo(slug: string, alt: string): Photo {
  return {
    id: slug,
    src: `/images/dishes/${slug}.jpg`,
    blurDataURL: BLUR_DATA_URLS[slug] ?? "",
    alt,
  };
}

// Featured cards in the menu (only items flagged `featured` in /data/menu.ts).
export const DISH_PHOTOS: Record<string, Photo> = {
  "pantera":             photo("pantera-01",   "La Pantera — hamburguesa gourmet con queso fundido"),
  "gamberra":            photo("gamberra-01",  "La Gamberra — hamburguesa con pan brioche oscuro"),
  "la-jefa":             photo("doble-01",     "La Jefa — hamburguesa doble con pulled pork"),
  "doble-ternera-pollo": photo("doble-01",     "Doble de ternera o pollo con queso fundido"),
  "rac-solomillo":       photo("solomillo-01", "Solomillo a la brasa con guarnición"),
  "boc-hr":              photo("bandeja-01",   "Bocadillo HR con carne BBQ y queso fundido"),
};

// Gallery — the four-photo editorial grid in "Carne, fuego, oficio".
export const GALLERY = {
  cocina:  photo("cocina-01",  "Cocina HR+ en plena hora punta, plancha encendida"),
  papas:   photo("papas-01",   "Patatas Río emplatadas con bacon crispy y salsa de queso"),
  queso:   photo("queso-01",   "Detalle de queso fundido sobre una hamburguesa"),
  bandeja: photo("bandeja-01", "Bandeja para compartir con varias hamburguesas"),
  pantera: photo("pantera-01", "La Pantera — elegida por el chef esta semana"),
} as const;

export function getDishPhoto(id: string): Photo | undefined {
  return DISH_PHOTOS[id];
}

// Oversized ingredient ticker that scrolls horizontally above the gallery.
// Keep this in sync with the actual menu vocabulary so it feels honest.
export const INGREDIENT_TICKER: ReadonlyArray<string> = [
  "Pan brioche",
  "Bacon ahumado",
  "Cheddar curado",
  "Mozzarella fundida",
  "Mayonesa de trufa",
  "Mermelada de bacon",
  "Cebolla caramelizada",
  "Pulled pork",
  "Salsa de yogur",
  "Patatas deluxe",
  "Aros de cebolla",
  "Donetes de queso",
  "Salsa Bourbon",
  "Rulo de cabra",
  "Algodón de azúcar",
];
